version: "3.7"
services:
  namenode:
    image: "docker.io/dockeralexandrtalan/hadoop"
    entrypoint: /bin/bash entrypoint.sh --command "hdfs start namenode" --config "/usr/local/lib/hadoop-2.9.2/etc/hadoop/hadoop-config.json"
    volumes:
      - ./hadoop-config:/usr/local/lib/hadoop-2.9.2/etc/hadoop/
      - ./hadoop-logs:/usr/local/lib/hadoop-2.9.2/logs/
    ports:
      - "9870:9870"
    networks:
      - hadoop
  datanode:
    image: "docker.io/dockeralexandrtalan/hadoop"
    entrypoint: /bin/bash entrypoint.sh --command "hdfs start datanode" --config "/usr/local/lib/hadoop-2.9.2/etc/hadoop/hadoop-config.json"
    volumes:
      - ./hadoop-config:/usr/local/lib/hadoop-2.9.2/etc/hadoop/
      - ./hadoop-logs:/usr/local/lib/hadoop-2.9.2/logs/
    networks:
      - hadoop
    depends_on:
      - namenode
networks:
  hadoop:
