version: "3.7"
services:
  namenode:
    container_name: namenode
    image: "docker.io/dockeralexandrtalan/hadoop_2.9.2"
    entrypoint: /bin/bash entrypoint.sh --command "hdfs start namenode" --config "$HADOOP_CONFIG/hadoop-config.json"
    volumes:
      - ./hadoop-config:$HADOOP_CONFIG
      - ./hadoop-logs:$HADOOP_LOGS
    ports:
      - "9870:9870"
    networks:
      - hadoop
  datanode_1:
    container_name: datanode_1
    image: "docker.io/dockeralexandrtalan/hadoop_2.9.2"
    entrypoint: /bin/bash entrypoint.sh --command "hdfs start datanode" --config "$HADOOP_CONFIG/hadoop-config.json"
    volumes:
      - ./hadoop-config:$HADOOP_CONFIG
      - ./hadoop-logs:$HADOOP_LOGS
    ports:
      - "50075:50075"
    networks:
      - hadoop
    depends_on:
      - namenode
  resourcemanager:
    container_name: resourcemanager
    image: "docker.io/dockeralexandrtalan/hadoop_2.9.2"
    entrypoint: /bin/bash entrypoint.sh --command "yarn start resourcemanager" --config "$HADOOP_CONFIG/hadoop-config.json"
    volumes:
      - ./hadoop-config:$HADOOP_CONFIG
      - ./hadoop-logs:$HADOOP_LOGS
    ports:
      - "12050:12050"
    networks:
      - hadoop
  nodemanager_1:
    container_name: nodemanager_1
    image: "docker.io/dockeralexandrtalan/hadoop_2.9.2"
    entrypoint: /bin/bash entrypoint.sh --command "yarn start nodemanager" --config "$HADOOP_CONFIG/hadoop-config.json"
    volumes:
      - ./hadoop-config:$HADOOP_CONFIG
      - ./hadoop-logs:$HADOOP_LOGS
    ports:
      - "8042:8042"
    networks:
      - hadoop
    depends_on:
      - resourcemanager
  nodemanager_2:
    container_name: nodemanager_2
    image: "docker.io/dockeralexandrtalan/hadoop_2.9.2"
    entrypoint: /bin/bash entrypoint.sh --command "yarn start nodemanager" --config "$HADOOP_CONFIG/hadoop-config.json"
    volumes:
      - ./hadoop-config:$HADOOP_CONFIG
      - ./hadoop-logs:$HADOOP_LOGS
    ports:
      - "8043:8042"
    networks:
      - hadoop
    depends_on:
      - resourcemanager
networks:
  hadoop: